### ISSUE TITLE
Stuck in "waiting for computation"

### ISSUE THREAD

**Issue by wp31** [golemfactory/g-flite#11] opened 2019-07-13 05:21 UTC
Used g_flite to compute a tiny .txt file and it went smoothly.  Subsequently, I attempted to try larger files, which at first would timeout, then had the timout time increased from 10min to 1hr.  Upon starting the tasks many times, using a combination of various different number of subtasks, from 2 up to 200, virtually none of them passed the state of "waiting for computation."

**Comment by kubkon** [comment] 2019-07-13 13:36
Hey! Thanks for testing the app and raising the issue–it's much appreciated! I'm not entirely sure what the cause for this behaviour could have been, and whether this is `g-flite` or Golem itself related (I'm betting on the latter, but you never know). Anyhow, in the meantime, to allow for easier config of a gWasm task using `g-flite`, I've added possibility to specify the timeout values in the command line.

With the new (release candidate) version of `g-flite`, you can specify both the task and subtask timeout values as follows:

```shell
g_flite some_input.txt some_output.txt --task_timeout 01:00:00 --subtask_timeout 01:00:00
```

Note that currently, the minimum timeout value is set at 1sec, or 00:00:01, and maximum at 23:59:59.

It is also possible to specify the bid value of the gWasm task directly from the command line with the following option:

```shell
g_flite some_input.txt some_output.txt --bid 1.0
```

You can get the new version of `g-flite` with this enabled from [here](https://github.com/golemfactory/g-flite/releases/tag/0.3.0-rc). @wp31 it'd be great if you could grab the new version and check whether there is any improvement at all, etc. :-)

**Comment by kubkon** [comment] 2019-07-13 16:22
Closing for now, as, after consultation with @wp31, reinstalling Golem helped. It seemed to be an issue with ports not being opened/configured correctly.

**Closed by kubkon** 2019-07-13 16:22 UTC
